#include "DZDiagnostics.h"
static FDZDiagnosticItem MakeDiag(EDZDiagnosticCode Code,int32 Priority,const TCHAR*Title,const TCHAR*Recommendation){FDZDiagnosticItem I;I.Code=Code;I.Priority=Priority;I.Title=Title;I.Recommendation=Recommendation;return I;}
FDZDiagnosticItem UDZDiagnosticsLibrary::CheckPower(float Allocation,float ChargeRatio){if(ChargeRatio<.1f)return MakeDiag(EDZDiagnosticCode::PowerLow,5,TEXT("Power reserve critical"),TEXT("Reduce non-essential loads and activate emergency distribution."));if(Allocation<.1f)return MakeDiag(EDZDiagnosticCode::PowerLow,3,TEXT("Power allocation low"),TEXT("Increase allocation or disable the dependent system."));return MakeDiag(EDZDiagnosticCode::None,0,TEXT("Power nominal"),TEXT("No action required."));}
FDZDiagnosticItem UDZDiagnosticsLibrary::CheckBattery(float ChargeRatio){if(ChargeRatio<.08f)return MakeDiag(EDZDiagnosticCode::BatteryLow,5,TEXT("Battery critical"),TEXT("Reduce propulsion and preserve life support."));if(ChargeRatio<.2f)return MakeDiag(EDZDiagnosticCode::BatteryLow,3,TEXT("Battery low"),TEXT("Schedule reactor recovery before extended exploration."));return MakeDiag(EDZDiagnosticCode::None,0,TEXT("Battery nominal"),TEXT("No action required."));}
FDZDiagnosticItem UDZDiagnosticsLibrary::CheckReactor(float Temperature,float Load){if(Temperature>80)return MakeDiag(EDZDiagnosticCode::ReactorHot,5,TEXT("Reactor temperature critical"),TEXT("Reduce load and restore cooling."));if(Load>.95f)return MakeDiag(EDZDiagnosticCode::ReactorHot,4,TEXT("Reactor load high"),TEXT("Redistribute power demand."));return MakeDiag(EDZDiagnosticCode::None,0,TEXT("Reactor nominal"),TEXT("No action required."));}
FDZDiagnosticItem UDZDiagnosticsLibrary::CheckCooling(float Efficiency){if(Efficiency<.25f)return MakeDiag(EDZDiagnosticCode::CoolingWeak,5,TEXT("Cooling failure risk"),TEXT("Inspect coolant loop and reduce reactor load."));if(Efficiency<.6f)return MakeDiag(EDZDiagnosticCode::CoolingWeak,3,TEXT("Cooling degraded"),TEXT("Assign engineering maintenance."));return MakeDiag(EDZDiagnosticCode::None,0,TEXT("Cooling nominal"),TEXT("No action required."));}
FDZDiagnosticItem UDZDiagnosticsLibrary::CheckHull(float Integrity,float DepthRatio){if(Integrity<.2f)return MakeDiag(EDZDiagnosticCode::HullWeak,5,TEXT("Hull critical"),TEXT("Reduce depth immediately and isolate damaged sections."));if(DepthRatio>.95f)return MakeDiag(EDZDiagnosticCode::HullWeak,4,TEXT("Depth margin exhausted"),TEXT("Ascend or route to a safer depth band."));if(Integrity<.5f)return MakeDiag(EDZDiagnosticCode::HullWeak,3,TEXT("Hull degraded"),TEXT("Schedule structural repair."));return MakeDiag(EDZDiagnosticCode::None,0,TEXT("Hull nominal"),TEXT("No action required."));}
FDZDiagnosticItem UDZDiagnosticsLibrary::CheckFlooding(float LitersPerSecond){if(LitersPerSecond>500)return MakeDiag(EDZDiagnosticCode::Flooding,5,TEXT("Flooding critical"),TEXT("Seal the compartment and operate pumps immediately."));if(LitersPerSecond>50)return MakeDiag(EDZDiagnosticCode::Flooding,4,TEXT("Flooding active"),TEXT("Locate leak source and close the bulkhead."));if(LitersPerSecond>0)return MakeDiag(EDZDiagnosticCode::Flooding,2,TEXT("Minor leak"),TEXT("Investigate and repair at the next safe opportunity."));return MakeDiag(EDZDiagnosticCode::None,0,TEXT("No flooding"),TEXT("No action required."));}
FDZDiagnosticItem UDZDiagnosticsLibrary::CheckOxygen(float Ratio){if(Ratio<.1f)return MakeDiag(EDZDiagnosticCode::OxygenLow,5,TEXT("Oxygen critical"),TEXT("Restore life support and restrict crew activity."));if(Ratio<.2f)return MakeDiag(EDZDiagnosticCode::OxygenLow,4,TEXT("Oxygen low"),TEXT("Conserve oxygen and inspect scrubber performance."));return MakeDiag(EDZDiagnosticCode::None,0,TEXT("Oxygen nominal"),TEXT("No action required."));}
FDZDiagnosticItem UDZDiagnosticsLibrary::CheckCO2(float Percent){if(Percent>4)return MakeDiag(EDZDiagnosticCode::CO2High,5,TEXT("CO2 critical"),TEXT("Restore scrubbers and ventilation immediately."));if(Percent>2.5f)return MakeDiag(EDZDiagnosticCode::CO2High,4,TEXT("CO2 high"),TEXT("Increase scrubber capacity."));if(Percent>1)return MakeDiag(EDZDiagnosticCode::CO2High,2,TEXT("CO2 elevated"),TEXT("Monitor continuously."));return MakeDiag(EDZDiagnosticCode::None,0,TEXT("CO2 nominal"),TEXT("No action required."));}
FDZDiagnosticItem UDZDiagnosticsLibrary::CheckSonar(float Noise,float Health){if(Health<.3f)return MakeDiag(EDZDiagnosticCode::SonarDegraded,4,TEXT("Sonar hardware degraded"),TEXT("Assign a sonar maintenance task."));if(Noise>.8f)return MakeDiag(EDZDiagnosticCode::SonarDegraded,3,TEXT("Acoustic noise high"),TEXT("Reduce active pings and mechanical noise."));return MakeDiag(EDZDiagnosticCode::None,0,TEXT("Sonar nominal"),TEXT("No action required."));}
FDZDiagnosticItem UDZDiagnosticsLibrary::CheckNavigation(float Confidence,float Drift){if(Confidence<.25f)return MakeDiag(EDZDiagnosticCode::NavigationUncertain,5,TEXT("Navigation unreliable"),TEXT("Acquire a sonar reference or surface navigation beacon."));if(Drift>500)return MakeDiag(EDZDiagnosticCode::NavigationUncertain,4,TEXT("Drift significant"),TEXT("Correct position with a known reference."));if(Confidence<.6f)return MakeDiag(EDZDiagnosticCode::NavigationUncertain,2,TEXT("Navigation uncertain"),TEXT("Collect additional mapping data."));return MakeDiag(EDZDiagnosticCode::None,0,TEXT("Navigation nominal"),TEXT("No action required."));}
FDZDiagnosticItem UDZDiagnosticsLibrary::CheckCommunication(float Quality,float Depth){if(Quality<.2f)return MakeDiag(EDZDiagnosticCode::CommunicationWeak,5,TEXT("Communications critical"),TEXT("Deploy relay or move toward a communication-safe sector."));if(Depth>6000&&Quality<.5f)return MakeDiag(EDZDiagnosticCode::CommunicationWeak,3,TEXT("Deep-link degraded"),TEXT("Use acoustic relay or buoy communications."));return MakeDiag(EDZDiagnosticCode::None,0,TEXT("Communications nominal"),TEXT("No action required."));}
FDZDiagnosticItem UDZDiagnosticsLibrary::CheckCrew(float Fatigue,float Morale){if(Fatigue>.9f)return MakeDiag(EDZDiagnosticCode::CrewFatigued,5,TEXT("Crew fatigue critical"),TEXT("Rotate personnel and cancel non-essential tasks."));if(Morale<.25f)return MakeDiag(EDZDiagnosticCode::CrewFatigued,4,TEXT("Crew morale low"),TEXT("Reduce crisis load and resolve active conflicts."));if(Fatigue>.7f)return MakeDiag(EDZDiagnosticCode::CrewFatigued,2,TEXT("Crew fatigue elevated"),TEXT("Plan a rest cycle."));return MakeDiag(EDZDiagnosticCode::None,0,TEXT("Crew nominal"),TEXT("No action required."));}
FDZDiagnosticItem UDZDiagnosticsLibrary::CheckResearch(float Progress,float Power){if(Power<.2f&&Progress<1)return MakeDiag(EDZDiagnosticCode::ResearchDelayed,3,TEXT("Laboratory power constrained"),TEXT("Allocate more power to research or pause analysis."));if(Progress<.25f)return MakeDiag(EDZDiagnosticCode::ResearchDelayed,1,TEXT("Research early stage"),TEXT("Continue analysis."));return MakeDiag(EDZDiagnosticCode::None,0,TEXT("Research progressing"),TEXT("No action required."));}
FDZDiagnosticItem UDZDiagnosticsLibrary::CheckSchedule(bool Open,int32 Minutes){if(!Open&&Minutes>=0)return MakeDiag(EDZDiagnosticCode::ScheduleClosed,2,TEXT("Window closed"),*FString::Printf(TEXT("Next operating window in %d minutes."),Minutes));if(!Open)return MakeDiag(EDZDiagnosticCode::ScheduleClosed,1,TEXT("No scheduled window"),TEXT("Add an operating window."));return MakeDiag(EDZDiagnosticCode::None,0,TEXT("Window open"),TEXT("Operations available."));}
